### ISSUE TITLE
There are too many ODScrollViewDelegate functions available

### ISSUE THREAD

**Issue by flyingBear66** [orcundeniz/ODScrollView#3]
There are too many `ODScrollViewDelegate` functions available, and maybe some of them can be optional so that dev wouldn't need to implement it all.

Because what I see in example extension where you implement `ODScrollViewDelegate`, 😨.
https://github.com/orcundeniz/ODScrollView/blob/e90ccdc13dd0f1aef6ab1babc4184be77e21e867/Example/ODScrollView/MainViewController.swift#L31

So, this can be a small improvement for easier usage. Let me know what you think?

**Comment by orcundeniz** [comment]
You're right. I made all of settings optional like UITableViewDelegate. You should implement functions if you don't want to use default settings.
