### ISSUE TITLE
Create ODScrollView by coding programmatically , not via storyboards or xib.

### ISSUE THREAD

**Issue by flyingBear66** [orcundeniz/ODScrollView#4]
During my review on your code, I saw that creating ODScrollView without storyboards or xib looks not possible, isn't it? 

So to implement that way also could be a nice improvement since a lot of people develops without storyboards. 

Let me know what you think!

**Comment by orcundeniz** [comment]
ODScrollView is just a UIScrollView. You can create ODScrollView with same way you create UIScrollView. It's up to you to create ODScrollView by using storyboard, xib or programmatically. Besides that you still can use UIScrollView's features. 
Thanks for feedback, I'm gonna update readme.
